# steps:
# - id: 'Staging the app using mvn appengine plugin'
#   name: 'gcr.io/cloud-builders/mvn'
#   args: ['package', 'appengine:stage']
# - id: "Deploy to app engine using gcloud image"
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy', cloudbuild.yaml']
# timeout: '1600s'


# steps:
# # Builds the application and deploys it to App Engine using Maven.
# - id: 'build_and_deploy'
#   name: 'gcr.io/cloud-builders/mvn'
#   args: ['package', 'appengine:deploy']
#   env:
#     - "GOOGLE_CLOUD_PROJECT=team9"

# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'src\main\webapp\WEB-INF\appengine-web.xml']
