steps:
- id: 'Staging the app using mvn appengine plugin'
  name: 'gcr.io/cloud-builders/mvn'
  args: ['package', 'appengine:stage']
- id: "Deploy to app engine using gcloud image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'codeu-spring-2019-team-9\cloudbuild.yaml']
timeout: '1600s'
